# Generated by Django 4.2.16 on 2024-11-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_description', models.CharField(max_length=200)),
                ('product_availability', models.BooleanField()),
                ('product_thumbnail', models.CharField(max_length=100)),
                ('max_order_quantity', models.IntegerField()),
            ],
        ),
    ]
