# Generated by Django 4.2.16 on 2024-11-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_products_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
