# Generated by Django 4.2.16 on 2024-11-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clients',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='mobile_number',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='clients',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clients',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clients',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
