# Generated by Django 4.1.10 on 2024-12-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_clients_city_clients_country_clients_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
    ]
